name: 'TASCAR xenial_dev'

on:
  schedule:
    - cron: '17 4 * * *'

  workflow_dispatch:
    

jobs:
  build:

    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - name: fetchtags
      run: git fetch --unshallow --tags
    - name: htchrepo
      run: sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys B7D6CDF547DA4ABD &&
           sudo apt-add-repository 'deb http://aptdev.hoertech.de/ xenial universe'
    - name: tascar
      run: sudo apt update &&
           sudo apt install --assume-yes git tascarpro libtascar-dev
    - name: showversion
      run: dpkg-query -l tascarpro
    - name: run
      run: tascar_renderfile -h
