name: ovclient_bionic

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: fetchtags
      run: git fetch --unshallow --tags
    - name: htchrepo
      run: sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys B7D6CDF547DA4ABD &&
           sudo apt-add-repository 'deb http://apt.hoertech.de/ bionic universe'
    - name: ovclient
      run: sudo apt update &&
           sudo apt install --assume-yes git ov-client
    - name: run
      run: ov-client & sleep 20;killall ov-client
